/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_Data;

import Conn.Methods2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Itsexceptional
 */
public class View_Ques extends javax.swing.JFrame {
    Connection con;
    PreparedStatement psmnt;
    ResultSet rs;
    /**
     * Creates new form View_Ques 
     */
    public View_Ques() {
        initComponents();
        filldatail();
         setLocation(280,200);
    }
         public final void filldatail()
    {
        try 
        {             
     String databasename="bug2db";
     String url="jdbc:mysql://localhost:3306/";
     String user="root";
     String pass="root";
     Class.forName("com.mysql.jdbc.Driver");  
     con= DriverManager.getConnection(url+databasename,user,pass);  
     PreparedStatement ps=con.prepareStatement("select * from courses");
     ResultSet r=ps.executeQuery();
     while (r.next()) {  
                course_combo.addItem(r.getString("course_name"));
        }
    }
       catch (ClassNotFoundException | SQLException e) 
        {  
            JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);        
            System.exit(0);  
        }  
    }
       /**
     *
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        course_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ques_combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW QUESTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 6, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Courses -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, -1, -1));

        course_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        course_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                course_comboItemStateChanged(evt);
            }
        });
        course_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_comboActionPerformed(evt);
            }
        });
        getContentPane().add(course_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 41, 121, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ques_ID -");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 46, -1, -1));

        ques_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        ques_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ques_comboItemStateChanged(evt);
            }
        });
        getContentPane().add(ques_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 41, 121, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 570, 133));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Answer One");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 249, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Answer Two");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 295, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Answer Three");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 341, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Answer Four");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 387, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correct Answer -");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 447, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 243, 256, -1));

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 289, 256, -1));

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 335, 256, -1));

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 381, 256, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 441, 256, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (3).png"))); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 243, 80, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (4).png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webp.net-resizeimage (2).png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 90, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quiz_m.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void course_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_comboActionPerformed
            
    }//GEN-LAST:event_course_comboActionPerformed

    private void course_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_course_comboItemStateChanged
                String course=""+course_combo.getSelectedItem();
                System.out.println(""+course);
                String sql="select * from "+course+"";
                ques_combo.removeAllItems();
                try
                {       
                    PreparedStatement ps=con.prepareStatement(sql);
                    ResultSet r=ps.executeQuery();
                    while(r.next())
                    { 
                        String ques_co=r.getString("ques_id");
                        ques_combo.addItem(ques_co);
                    }
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }
    }//GEN-LAST:event_course_comboItemStateChanged

    private void ques_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ques_comboItemStateChanged
            String ques=""+ques_combo.getSelectedItem();
            String cor=""+course_combo.getSelectedItem();
            String sql="select * from "+cor+" where ques_id='"+ques+"'";
            try
            {
                psmnt=con.prepareStatement(sql);
                rs=psmnt.executeQuery();
                while(rs.next())
                {
                    String question=rs.getString("questions");
                    jTextArea1.setText(question);
                    String ans_one=rs.getString("answer_one");
                    jTextField1.setText(ans_one);
                    String ans_two=rs.getString("answer_two");
                    jTextField2.setText(ans_two);
                    String ans_three=rs.getString("answer_three");
                    jTextField3.setText(ans_three);
                    String ans_four=rs.getString("answer_four");
                    jTextField4.setText(ans_four);
                    String cor_ans=rs.getString("correct_ans");
                    jTextField5.setText(cor_ans);
                }
             
            }
            catch(SQLException ex)
            {
                  JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_comboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                String course=""+course_combo.getSelectedItem();
                String queid=""+ques_combo.getSelectedItem();
                String ques=jTextArea1.getText().trim();
                String ansone=jTextField1.getText().trim();
                String anstwo=jTextField2.getText().trim();
                String ansthree=jTextField3.getText().trim();
                String ansfour=jTextField4.getText().trim();
                String corans=jTextField5.getText().trim();
        try {
            if(new Methods2().UpdateQues(queid, course, ques, ansone, anstwo, ansthree, ansfour, corans)>0)
            {
                JOptionPane.showMessageDialog(null,"Question Updated Successfully !!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cannot Connect to Database");
            }
        } catch (Exception ex) {
            Logger.getLogger(View_Ques.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                String course=""+course_combo.getSelectedItem();
                String quesid=""+ques_combo.getSelectedItem();
                String ansone=jTextField1.getText().trim();
                String anstwo=jTextField2.getText().trim();
                String ansthree=jTextField3.getText().trim();
                String ansfour=jTextField4.getText().trim();
                String corans=jTextField5.getText().trim();
        try {
            if(new Methods2().DeleteQues(course, quesid, course, quesid, course, quesid, course, quesid)>0)
            {
                JOptionPane.showMessageDialog(null,"Question Deleted Successfully !!");
                new View_Ques().setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cannot Connect to Database");
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(View_Ques.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setEditable(true);
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
        jTextField3.setEditable(true);
        jTextField4.setEditable(true);
        jTextField5.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                new Questons().setVisible(true);
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Ques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Ques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> course_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> ques_combo;
    // End of variables declaration//GEN-END:variables
}
