/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import conn.Methods;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Itsexceptional
 */
public class Submit extends javax.swing.JFrame {

    /**
     * Creates new form Submit
     */
    public Submit(String total,String attempt,String correct,String incorrect,String remain,String name) {
        initComponents();
       jLabel7.setText(name);
       totalQ.setText(total);
       attemptedQ.setText(attempt);
       remainQ.setText(remain);
       corr.setText(correct);
       incorr.setText(incorrect);
       try{
       int a=Integer.parseInt(corr.getText().trim());
       int b=Integer.parseInt(totalQ.getText().trim());
       int r=(a*100)/b;
       result.setText(""+r);
       }
       catch(ArithmeticException ex)
       {
           ex.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalQ = new javax.swing.JTextField();
        attemptedQ = new javax.swing.JTextField();
        remainQ = new javax.swing.JTextField();
        corr = new javax.swing.JTextField();
        incorr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalQ.setEditable(false);
        totalQ.setText("                     ");
        getContentPane().add(totalQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 49, 108, -1));

        attemptedQ.setEditable(false);
        attemptedQ.setText("                    ");
        getContentPane().add(attemptedQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 95, 108, -1));

        remainQ.setEditable(false);
        remainQ.setText("                   ");
        remainQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainQActionPerformed(evt);
            }
        });
        getContentPane().add(remainQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 141, 108, -1));

        corr.setEditable(false);
        corr.setText("                     ");
        getContentPane().add(corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 187, 108, -1));

        incorr.setEditable(false);
        incorr.setText("                  ");
        getContentPane().add(incorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 233, 108, -1));

        jLabel1.setText("Total Questions -");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, -1, -1));

        jLabel2.setText("Attempted Questions -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 101, -1, -1));

        jLabel3.setText("Remaining Questions -");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 147, -1, -1));

        jLabel4.setText("Correct Questions -");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 193, -1, -1));

        jLabel5.setText("Incorrect Questions -");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 239, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/as.png"))); // NOI18N
        jButton1.setText("Save Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, 40));

        jLabel6.setText("Result of -");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 15, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 16, -1, -1));

        jLabel8.setText("Percentage -");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, -1, -1));

        result.setText(" ");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 279, 108, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quiz_hauptstadt.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remainQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainQActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String un=jLabel7.getText();
               String res=result.getText();
        try {
            if(new Methods().updateResults(un, res)>0)
            {
                JOptionPane.showMessageDialog(null," Test Result Saved ");
                new Start_Quiz(un).setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cannot Connect to Database");
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Submit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submit("","","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attemptedQ;
    private javax.swing.JTextField corr;
    private javax.swing.JTextField incorr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField remainQ;
    private javax.swing.JTextField result;
    private javax.swing.JTextField totalQ;
    // End of variables declaration//GEN-END:variables
}
